spring.application.name=btvn

# ===============================
# PostgreSQL Datasource Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/vidu
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 1. Log của toàn bộ ứng dụng ở mức INFO
logging.level.root=INFO

# 2. Log của Hibernate/JPA ở mức DEBUG (hiển thị câu lệnh SQL gửi xuống DB)
logging.level.org.hibernate.SQL=DEBUG

# 3. Log của package com.medical.service ở mức TRACE
logging.level.java.spring.btvn.service=TRACE

# 1. Đường dẫn và tên file log chính
logging.file.name=logs/patient_web_service.log

# 2. Định dạng tên file lưu trữ khi nén (.gz) theo ngày và chỉ số xoay vòng
logging.logback.rollingpolicy.file-name-pattern=logs/patient_web_service-%d{yyyy-MM-dd}.%i.log.gz

# 3. Kích thước tối đa của mỗi file log trước khi rollover
logging.logback.rollingpolicy.max-file-size=2MB

# 4. Thời gian lưu trữ tối đa (7 ngày)
logging.logback.rollingpolicy.max-history=7